### ISSUE TITLE
afk

### ISSUE THREAD

**Issue by craterXO** [XaloraLabs/XaloraClient#3]
C:\Users\Sayan\Documents\GitHub\XaloraClient\api\afk.js:14
    if (newsettings.api["afk page"].enabled !== true || !req.session || !req.session.userinfo) {
                                    ^

TypeError: Cannot read properties of undefined (reading 'enabled')
    at C:\Users\Sayan\Documents\GitHub\XaloraClient\api\afk.js:14:37
    at C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express-ws\lib\wrap-middleware.js:13:9
    at Layer.handle [as handle_request] (C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\Sayan\Documents\GitHub\XaloraClient\node_modules\express\lib\router\index.js:280:10)
    at C:\Users\Sayan\Documents\GitHub\XaloraClient\index.js:158:3

Node.js v20.16.0

**Comment by ThaYTOfficial** [comment]
ok 💀

**Comment by VSPDecoderZZ-Official** [comment]
Hi C:\Users\Sayan 
💀

**Comment by TrivCodez** [comment]
`newsettings.api["afk page"]` is undefined.... idk who did this breh... buggy code fr

**Comment by ThaYTOfficial** [comment]
Fixed in update Alpha 0.3
